import { createPathBasedClient } from "openapi-fetch";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

export const client = createPathBasedClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/", headers: {
        'API-KEY': '3897f0cc-ec64-4ebd-9093-9d4dbb072be0'
    }
});

