import type {paths} from "./schema";
import createClient from "openapi-fetch"; // generated by openapi-typescript


export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: {
        'API-KEY': '3897f0cc-ec64-4ebd-9093-9d4dbb072be0'
    }
});

